[workspace]
members = [
    "claims",
    "connect",
    "did",
    "home-protocol",
    "home-node",
#    "forgetfulfuse", # causes compilation problems on Mac, still experimental
    "keyvault",
    "osg-rpc-storage",
    "prometheus",
    "prometheus-cli",
    "prometheus-tester",
    "storage",
    "test",
    "examples/TheButton"
]
